Repository thunder/thunder-distribution, pull requests merged in 2020-06, with the labels that each got.

#230 Fix/testing
  composer.json
  config/install/scheduler.settings.yml
  drupal-org.make
  tests/src/FunctionalJavascript/Integration/AutosaveFormTest.php
  tests/src/Traits/ThunderTestTrait.php
Labels: test-min

#232 Release/3.4.6
  CHANGELOG.md
  composer.json
  drupal-org-core.make
  scripts/travis/03-build-thunder-drush.sh
  thunder.info.yml
Labels: test-min

#231 Issue #3145637 by chr.fritsch, volkerk: Release Thunder 3.5.0
  CHANGELOG.md
  drupal-org-core.make
  scripts/travis/03-build-thunder-drush.sh
  thunder.info.yml
Labels: test-min

#236 Allow installation of update_helper 2
  composer.json
Labels: test-performance

#238 Release/3.5.1
  CHANGELOG.md
  drupal-org-core.make
  thunder.info.yml
Labels: test-min, test-performance, test-upgrade

#239 Release/3.4.8
  CHANGELOG.md
  composer.json
  drupal-org-core.make
  tests/src/Functional/Installer/ThunderInstallerGermanTest.php
  thunder.info.yml
Labels: test-min, test-performance, test-upgrade

#240 build: use GH Actions for upgrade testing
  .github/labels.yml
  .github/workflows/test.yml
Labels: test-min, test-performance, test-upgrade

#245 Issue #3064540 by chr.fritsch, daniel.bosen: Remove unneded packages
  composer.json
Labels: test-min

#248 build: update simple_sitemap module
  composer.json
Labels: test-min, test-upgrade

#250 Issue #3133327 by chr.fritsch: Remove simple_gmap from composer.json and let composer figure out the right version
  composer.json
Labels: test-min, test-upgrade

#252 Remove riddle integration
  .github/workflows/test.yml
  composer.json
  modules/thunder_article/modules/thunder_riddle/README.md
  modules/thunder_article/modules/thunder_riddle/config/optional/core.entity_form_display.media.riddle.default.yml
  modules/thunder_article/modules/thunder_riddle/config/optional/core.entity_form_display.paragraph.riddle.default.yml
  modules/thunder_article/modules/thunder_riddle/config/optional/core.entity_view_display.media.riddle.default.yml
  modules/thunder_article/modules/thunder_riddle/config/optional/core.entity_view_display.media.riddle.thumbnail.yml
  modules/thunder_article/modules/thunder_riddle/config/optional/core.entity_view_display.paragraph.riddle.default.yml
  modules/thunder_article/modules/thunder_riddle/config/optional/core.entity_view_display.paragraph.riddle.preview.yml
  modules/thunder_article/modules/thunder_riddle/config/optional/entity_browser.browser.riddle_browser.yml
  modules/thunder_article/modules/thunder_riddle/config/optional/field.field.media.riddle.field_riddle_id.yml
  modules/thunder_article/modules/thunder_riddle/config/optional/field.field.paragraph.riddle.field_riddle.yml
  modules/thunder_article/modules/thunder_riddle/config/optional/field.storage.media.field_riddle_id.yml
  modules/thunder_article/modules/thunder_riddle/config/optional/field.storage.paragraph.field_riddle.yml
  modules/thunder_article/modules/thunder_riddle/config/optional/media.type.riddle.yml
  modules/thunder_article/modules/thunder_riddle/config/optional/paragraphs.paragraphs_type.riddle.yml
  modules/thunder_article/modules/thunder_riddle/config/schema/thunder_riddle.schema.yml
  modules/thunder_article/modules/thunder_riddle/css/media_entity_browser.view.css
  modules/thunder_article/modules/thunder_riddle/src/Plugin/EntityBrowser/Widget/RiddleView.php
  modules/thunder_article/modules/thunder_riddle/thunder_riddle.info.yml
  modules/thunder_article/modules/thunder_riddle/thunder_riddle.install
  modules/thunder_article/modules/thunder_riddle/thunder_riddle.libraries.yml
  modules/thunder_article/modules/thunder_riddle/thunder_riddle.module
  modules/thunder_demo/content/node/0bd5c257-2231-450f-b4c2-ab156af7b78d.json
  modules/thunder_demo/content/paragraph/11e7fd11-cca5-4d17-b29b-fa67a21b2f05.json
  modules/thunder_demo/content/paragraph/f8e9a0e7-7db3-4642-8f41-479975ea88e5.json
  modules/thunder_media/thunder_media.module
  src/Plugin/Thunder/OptionalModule/NexxIntegration.php
  src/Plugin/Thunder/OptionalModule/RiddleIntegration.php
  tests/src/Functional/InstalledConfigurationTest.php
  tests/src/Functional/ModuleUninstallTest.php
  tests/src/FunctionalJavascript/Integration/RiddleTest.php
  tests/src/FunctionalJavascript/ThunderMediaTestTrait.php
  thunder.install
Labels: test-min, test-upgrade

#243 Backport commits
  .github/labels.yml
  .github/workflows/test.yml
  .travis.yml
  README.md
  composer.json
  docs/development.md
  docs/pull-screenshots-from-travis-ci.md
  scripts/development/build-thunder.sh
  scripts/travis/00-keep-travis-running.sh
  scripts/travis/01-setup-environment.sh
  scripts/travis/02-before-install.sh
  scripts/travis/03-build-thunder-composer.sh
  scripts/travis/03-build-thunder-drush.sh
  scripts/travis/03-build-thunder2.sh
  scripts/travis/03-use-thunder-artifact.sh
  scripts/travis/04-install-thunder.sh
  scripts/travis/04-use-database-artifact.sh
  scripts/travis/05-setup-tests.sh
  scripts/travis/05-update-2-3.sh
  scripts/travis/06-run-config-tests.sh
  scripts/travis/06-run-tests.sh
  scripts/travis/06-test-source-code.sh
  scripts/travis/07-upload-artifacts-to-s3.sh
  scripts/travis/08-build-docker-performance-image.sh
Labels: test-min, test-upgrade
