Repository thunder/thunder-distribution, pull requests merged in 2022-05, with the labels that each got.

#557 Fix paragraphs paste min version
  composer.json
Labels: test-min

#559 Update blazy and slick min versions
  composer.json
Labels: test-min, test-upgrade

#558 Issue #3278186: Release Thunder 6.3.7
  CHANGELOG.md
  thunder.info.yml
Labels: test-min, test-upgrade

#565 fix: rename node form class
  modules/thunder_article/src/ThunderNodeFormHelper.php
  modules/thunder_article/thunder_article.module
Labels: test-upgrade

#573 Initial article form styling
  config/optional/core.entity_form_display.node.article.default.yml
  config/update/thunder_post_update_0001_upgrade_to_thunder7.yml
  modules/thunder_article/css/article-form.css
  modules/thunder_article/src/ThunderNodeFormHelper.php
  modules/thunder_article/thunder_article.libraries.yml
Labels: test-upgrade

#526 Morpho paragraph preview
  config/optional/core.entity_view_display.media.gallery.paragraph_preview.yml
  config/optional/core.entity_view_display.media.image.paragraph_preview.yml
  config/optional/core.entity_view_display.media.instagram.paragraph_preview.yml
  config/optional/core.entity_view_display.media.twitter.paragraph_preview.yml
  config/optional/core.entity_view_display.media.video.paragraph_preview.yml
  config/update/thunder_post_update_0001_upgrade_to_thunder7.yml
  modules/thunder_paragraphs/css/paragraphs.widget.css
  modules/thunder_paragraphs/thunder_paragraphs.libraries.yml
  modules/thunder_paragraphs/thunder_paragraphs.module
Labels: test-upgrade

#575 Fix responsive image style dependency
  composer.json
  config/optional/core.entity_view_display.media.image.default.yml
  config/optional/core.entity_view_display.media.image.slick.yml
  config/update/thunder_update_8324.yml
  thunder.install
  updates_checklist.yml
Labels: test-min, test-upgrade

#576 Forward ports of 6.3.x changes
  composer.json
  config/optional/core.entity_view_display.media.image.default.yml
  config/optional/core.entity_view_display.media.image.slick.yml
  docs/developer-guide/migration/migrate-6-7.md
  thunder.install
Labels: test-upgrade

#549 Remove legacy themes
  .github/workflows/tests.yml
  composer.json
  config/optional/block.block.seven_breadcrumbs.yml
  config/optional/block.block.seven_content.yml
  config/optional/block.block.seven_help.yml
  config/optional/block.block.seven_local_actions.yml
  config/optional/block.block.seven_login.yml
  config/optional/block.block.seven_messages.yml
  config/optional/block.block.seven_page_title.yml
  config/optional/block.block.seven_primary_local_tasks.yml
  config/optional/block.block.seven_secondary_local_tasks.yml
  docs/developer-guide/migration/migrate-6-7.md
  docs/user-guide/feature-overview.md
  modules/thunder_demo/thunder_demo.module
  modules/thunder_media/css/bartik_slick_fix.css
  modules/thunder_media/thunder_media.libraries.yml
  modules/thunder_search/config/optional/block.block.seven_exposedformcontent_search_apipage_1.yml
  modules/thunder_search/config/optional/block.block.seven_facet_author.yml
  modules/thunder_search/config/optional/block.block.seven_facet_channel.yml
  modules/thunder_search/config/optional/block.block.seven_facet_promoted.yml
  modules/thunder_search/config/optional/block.block.seven_facet_status.yml
  modules/thunder_search/config/optional/block.block.seven_facet_sticky.yml
  modules/thunder_search/config/optional/block.block.seven_facet_tags.yml
  modules/thunder_search/config/optional/block.block.seven_facet_type.yml
  modules/thunder_search/config/optional/block.block.thunder_admin_exposedformcontent_search_apipage_1.yml
  modules/thunder_search/config/optional/block.block.thunder_admin_facet_author.yml
  modules/thunder_search/config/optional/block.block.thunder_admin_facet_channel.yml
  modules/thunder_search/config/optional/block.block.thunder_admin_facet_promoted.yml
  modules/thunder_search/config/optional/block.block.thunder_admin_facet_status.yml
  modules/thunder_search/config/optional/block.block.thunder_admin_facet_sticky.yml
  modules/thunder_search/config/optional/block.block.thunder_admin_facet_tags.yml
  modules/thunder_search/config/optional/block.block.thunder_admin_facet_type.yml
  tests/src/FunctionalJavascript/ChannelsTagsTest.php
  themes/thunder_base/config/optional/image.style.media_image.yml
  themes/thunder_base/config/optional/image.style.media_image_mobile.yml
  themes/thunder_base/config/optional/image.style.media_image_tablet.yml
  themes/thunder_base/config/optional/responsive_image.styles.media_image.yml
  themes/thunder_base/config/schema/thunder_base.schema.yml
  themes/thunder_base/css/colors.css
  themes/thunder_base/css/components/taxonomy-term.css
  themes/thunder_base/css/components/tour.theme.css
  themes/thunder_base/css/node-image-field-fix.css
  themes/thunder_base/css/thunder.css
  themes/thunder_base/favicon.ico
  themes/thunder_base/images/Thunder-white_400x90.png
  themes/thunder_base/logo.svg
  themes/thunder_base/templates/field--paragraph--field-text--quote.html.twig
  themes/thunder_base/templates/node--article--teaser.html.twig
  themes/thunder_base/templates/taxonomy-term.html.twig
  themes/thunder_base/thunder_base.breakpoints.yml
  themes/thunder_base/thunder_base.info.yml
  themes/thunder_base/thunder_base.libraries.yml
  thunder.info.yml
Labels: test-upgrade
